version: "3"
services: 
    app: 
        image: 'node:latest'
        container_name: 'app'
        restart: 'always'
        working_dir: '/app'
        volumes: 
            - '.:/app'
        ports: 
            - '${FORWARD_APP_PORT:-3000}:3000'
        command: >
            bash -c "yarn install && yarn start-dev"
