# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node Tests

  
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Install yarn'
        run: npm install -g yarn
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: 'yarn install and test'
        run: | 
          yarn 
          yarn test
